const users = [
    {
        id: '',
        title: 'Graphical Reservation',
        github: 'https://github.com/afredknot/Table-Reservation',
        deployed: 'https://graphical-restaurant.herokuapp.com/',
        image_file: '',
        description: '',
        tools:'',
    },
    {
        id: '',
        title: 'More Than A Game',
        github: 'https://github.com/mfrabott/More-Than-A-Game',
        deployed: 'https://mfrabott.github.io/More-Than-A-Game/',
        image_file: '',
        description: '',
        tools:'',
    },
    {
        id: '',
        title: 'Weather Dashboard',
        github: 'https://github.com/mfrabott/weather-dashboard-mjf',
        deployed: 'https://mfrabott.github.io/weather-dashboard-mjf',
        image_file: '',
        description: '',
        tools:'',
    },
    {
        id: '',
        title: 'To Do List',
        github: 'Mr',
        deployed: 'https://mfrabott.github.io/frabott-daily-agenda-calendar/',
        image_file: '',
        description: '',
        tools:'',
    },

    {
        id: '',
        title: 'Just Another Text Editor',
        github: 'https://github.com/mfrabott/pwa-text-editor',
        deployed: 'https://powerful-wildwood-70016.herokuapp.com/',
        image_file: '',
        description: '',
        tools:'',
    },
    {
        id: '',
        title: 'Code Quiz',
        github: 'https://github.com/mfrabott/frabott-javascript-code-quiz',
        deployed: 'https://mfrabott.github.io/frabott-javascript-code-quiz/',
        image_file: '',
        description: '',
        tools:'',
    },
]