const myProjects = [
    {
        id: 1,
        title: 'Graphical Reservation',
        github: 'https://github.com/afredknot/table-reservation',
        deployed: 'https://graphical-restaurant.herokuapp.com',
        image_file: 'graphical-rest.png',
        description: '',
        tools:'',
    },
    {
        id: 2,
        title: 'More Than A Game',
        github: 'https://github.com/mfrabott/more-than-a-game',
        deployed: 'https://mfrabott.github.io/More-Than-A-Game/',
        image_file: 'moreThanAGame2.png',
        description: '',
        tools:'',
    },
    {
        id: 3,
        title: 'Weather Dashboard',
        github: 'https://github.com/mfrabott/weather-dashboard-mjf',
        deployed: 'https://mfrabott.github.io/weather-dashboard-mjf',
        image_file: 'weather-dashboard.png',
        description: '',
        tools:'',
    },
    {
        id: 4,
        title: 'Work Day Scheduler',
        github: 'https://github.com/mfrabott/frabott-daily-agenda-calendar',
        deployed: 'https://mfrabott.github.io/frabott-daily-agenda-calendar',
        image_file: 'Work-Day-Scheduler.gif',
        description: '',
        tools:'',
    },
    {
        id: 5,
        title: 'Just Another Text Editor',
        github: 'https://github.com/mfrabott/pwa-text-editor',
        deployed: 'https://powerful-wildwood-70016.herokuapp.com',
        image_file: 'JATE.png',
        description: '',
        tools:'',
    },
    {
        id: 6,
        title: 'Code Quiz',
        github: 'https://github.com/mfrabott/frabott-javascript-code-quiz',
        deployed: 'https://mfrabott.github.io/frabott-javascript-code-quiz',
        image_file: 'Code-Quiz.gif',
        description: '',
        tools:'',
    },
    // {
    //     id: 7,
    //     title: 'Note Taker',
    //     github: 'https://github.com/mfrabott/note-taker-express-server',
    //     deployed: 'https://shielded-fortress-69743.herokuapp.com',
    //     image_file: 'note-taker.png',
    //     description: '',
    //     tools:'',
    // },
]
export default myProjects;
