const users = [
    {
        id: '',
        title: 'Graphical Reservation',
        github: 'https://github.com/afredknot/Table-Reservation',
        deployed: 'https://graphical-restaurant.herokuapp.com/',
        image_file: '../assets/images/graphical-rest.png',
        description: '',
        tools:'',
    },
    {
        id: '',
        title: 'More Than A Game',
        github: 'https://github.com/mfrabott/More-Than-A-Game',
        deployed: 'https://mfrabott.github.io/More-Than-A-Game/',
        image_file: '../assets/images/weather-dashboard.png',
        description: '',
        tools:'',
    },
    {
        id: '',
        title: 'Weather Dashboard',
        github: 'https://github.com/mfrabott/weather-dashboard-mjf',
        deployed: 'https://mfrabott.github.io/weather-dashboard-mjf',
        image_file: '../assets/images/weather-dashboard.png',
        description: '',
        tools:'',
    },
    {
        id: '',
        title: 'Work Day Scheduler',
        github: 'https://github.com/mfrabott/frabott-daily-agenda-calendar',
        deployed: 'https://mfrabott.github.io/frabott-daily-agenda-calendar/',
        image_file: '../assets/images/Work-Day-Scheduler.gif',
        description: '',
        tools:'',
    },
    {
        id: '',
        title: 'Just Another Text Editor',
        github: 'https://github.com/mfrabott/pwa-text-editor',
        deployed: 'https://powerful-wildwood-70016.herokuapp.com/',
        image_file: '../assets/images/JATE.png',
        description: '',
        tools:'',
    },
    {
        id: '',
        title: 'Code Quiz',
        github: 'https://github.com/mfrabott/frabott-javascript-code-quiz',
        deployed: 'https://mfrabott.github.io/frabott-javascript-code-quiz/',
        image_file: '../assets/images/Code-Quiz.gif',
        description: '',
        tools:'',
    },
    {
        id: '',
        title: 'Note Taker',
        github: 'https://github.com/mfrabott/note-taker-Express-Server',
        deployed: 'https://shielded-fortress-69743.herokuapp.com/',
        image_file: '../assets/images/note-taker.png',
        description: '',
        tools:'',
    },
]